export default {
  alert: {
    container: {
      base:
        "rounded-md p-4 flex",
      info: "bg-blue-50",
      success: "bg-green-50",
      warning: "bg-yellow-50",
      error: "bg-red-50",
    },
    leadingIcon: {
      base: "h-5 w-5",
      info: "text-blue-400",
      success: "text-green-400",
      warning: "text-yellow-400",
      error: "text-red-400",
    },
    content: {
      base: "text-sm font-medium",
      info: "text-blue-700",
      success: "text-green-800",
      warning: "text-yellow-700",
      error: "text-red-700",
    },
    close: {
      base: "inline-flex rounded-md p-1.5 focus:outline-none focus:ring-2 focus:ring-offset-2",
      info: "bg-blue-50 text-blue-500 hover:bg-blue-100 focus:ring-offset-blue-50 focus:ring-blue-600",
      success: "bg-green-50 text-green-500 hover:bg-green-100 focus:ring-offset-green-50 focus:ring-green-600",
      warning: "bg-yellow-50 text-yellow-500 hover:bg-yellow-100 focus:ring-offset-yellow-50 focus:ring-yellow-600",
      error: "bg-red-50 text-red-500 hover:bg-red-100 focus:ring-offset-red-50 focus:ring-red-600",
    },
  },
  button: {
    base: "items-center px-4 py-2 border shadow-sm text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2",
    block: "block w-full",
    inline: "inline-flex",
    variants: {
      root: {
        fill: "focus:ring-indigo-500",
        outline: "",
        link: "",
        disabled: "opacity-50 cursor-not-allowed",
      },
      default: {
        fill: "border-gray-300 text-gray-700 bg-white hover:bg-gray-50",
        outline: "",
        link: "",
        disabled: "bg-gray-300",
      },
      primary: {
        fill: "border-transparent text-white bg-indigo-600 hover:bg-indigo-700",
        outline:
          "",
        link: "",
        disabled: "bg-gray-400",
      },
      secondary: {
        fill: "border-transparent text-indigo-700 bg-indigo-100 hover:bg-indigo-200",
        outline: "",
        link: "",
        disabled: "bg-indigo-50 text-indigo-400",
      },
      "danger.primary": {
        fill: "border-transparent bg-red-600 text-white hover:bg-red-700 focus:ring-red-500",
        outline: "",
        link: "",
        disabled: "bg-red-50",
      },
      "danger.secondary": {
        fill: "border-transparent text-red-700 bg-red-100 hover:bg-red-200 focus:ring-red-500",
        outline: "",
        link: "",
        disabled: "bg-red-50",
      },
    },
    // icon classes
    leadingIcon: "-ml-1 mr-2 h-5 w-5",
    trailingIcon: "ml-2 -mr-1 h-5 w-5",
  },
  icon: {
    base: "fill-current w-4 h-4",
  },
  input: {
    root: "",
    container: "mt-1 relative rounded-md shadow-sm",
    input: {
      root: "shadow-sm block w-full sm:text-sm rounded-md",
      base: "focus:ring-indigo-500 focus:border-indigo-500 border-gray-300",
      leading: "pl-10",
      trailing: "pr-10",
      error:
        "pr-10 border-red-300 text-red-900 placeholder-red-300 focus:outline-none focus:ring-red-500 focus:border-red-500",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
      readonly: "bg-gray-200",
    },
    label: {
      root: "block text-sm font-medium",
      base: "text-gray-700",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    leadingIcon: {
      root: "h-5 w-5",
      base: "text-gray-400",
      container:
        "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none",
      error: "text-red-500",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
    },
    trailingIcon: {
      root: "h-5 w-5",
      base: "text-gray-400",
      container: "absolute inset-y-0 right-0 pr-3 flex items-center",
      error: "text-red-500",
      warning: "",
      info: "",
      success: "text-green-600",
      disabled: "text-gray-500",
    },
    help: {
      root: "mt-2 text-sm",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "",
    },
  },
  textarea: {
    root: "",
    container: "mt-1 relative rounded-md shadow-sm",
    textarea: {
      root: "shadow-sm block w-full sm:text-sm rounded-md leading-tight",
      base: "focus:ring-indigo-500 focus:border-indigo-500 border-gray-300",
      leading: "pl-10",
      trailing: "pr-10",
      error:
        "pr-10 border-red-300 text-red-900 placeholder-red-300 focus:outline-none focus:ring-red-500 focus:border-red-500",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
      readonly: "bg-gray-200",
    },
    label: {
      root: "block text-sm font-medium",
      base: "text-gray-700",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    leadingIcon: {
      root: "h-5 w-5",
      base: "text-gray-400",
      container:
        "absolute left-0 top-0 pt-3 pl-3 flex items-center pointer-events-none",
      error: "text-red-500",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
    },
    trailingIcon: {
      root: "h-5 w-5",
      base: "text-gray-400",
      container: "absolute pt-3 top-0 right-0 pr-3 flex items-center",
      error: "text-red-500",
      warning: "",
      info: "",
      success: "text-green-600",
      disabled: "text-gray-500",
    },
    help: {
      root: "mt-2 text-sm",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "",
    },
  },
  switch: {
    root: "flex items-center",
    label: {
      base: "font-medium text-sm",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-300",
    },
    back: {
      base:
        "relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
      checked: "bg-green-600",
      unchecked: "bg-gray-300",
      disabled: "opacity-50",
    },
    front: {
      base:
        "inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200",
      checked: "translate-x-5",
      unchecked: "translate-x-0",
      disabled: "bg-gray-100",
    },
    help: {
      root: "mt-2 text-sm",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "",
    },
  },
  select: {
    root: "",
    container: "mt-1 relative rounded-md shadow-sm",
    select: {
      root: "shadow-sm block w-full sm:text-sm rounded-md",
      leading: "pl-10",
      trailing: "pr-20",
      base: "",
      base_multiple: "block w-full",
      error:
        "border border-red-500 text-red-600 placeholder-red-300 focus:border-red-500 focus:shadow-outline-red",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
      readonly: "bg-gray-200",
    },
    label: {
      root: "block text-sm text-left font-medium leading-5",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    leadingIcon: {
      root: "h-5 w-5",
      base: "text-gray-400",
      container:
        "absolute inset-y-0 left-0 flex items-center pointer-events-none px-2",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
    },
    trailingIcon: {
      root: "h-5 w-5",
      base: "text-gray-400",
      container: "absolute inset-y-0 right-0 pr-10 flex items-center",
      error: "text-red-500",
      warning: "",
      info: "",
      success: "text-green-600",
      disabled: "text-gray-500",
    },
    help: {
      root: "block text-sm mt-1 text-left font-medium leading-5",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "",
    },
  },
  checkbox: {
    root: "",
    container: "flex items-center",
    input: {
      root: "h-4 w-4 border-gray-300 rounded",
      base: "focus:ring-indigo-500 text-indigo-600",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "text-green-400",
      disabled: "text-gray-500",
      readonly: "",
    },
    label: {
      root: "block text-sm font-medium",
      base: "text-gray-700",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    text: {
      root: "ml-2 block text-sm",
      base: "text-gray-900",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    help: {
      root: "mt-2 text-sm",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "text-green-400",
    },
  },
  radio: {
    root: "",
    container: "flex items-center",
    input: {
      root: "h-4 w-4 border-gray-300",
      base: "focus:ring-indigo-500 text-indigo-600",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "text-gray-500",
      readonly: "",
    },
    label: {
      root: "block text-sm font-medium",
      base: "text-gray-700",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    text: {
      root: "ml-2 block text-sm",
      base: "text-gray-900",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    help: {
      root: "mt-2 text-sm",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "",
    },
  },
  // used for checkbox or radio group
  group: {
    root: "",
    container: "",
    container_vertical: "flex-col",
    container_horizontal: "flex items-center",
    label: {
      root: "block text-sm font-medium",
      base: "text-gray-700",
      error: "text-red-600",
      warning: "",
      info: "",
      success: "",
      disabled: "",
    },
    help: {
      root: "mt-2 text-sm",
      base: "text-gray-600",
      error: "text-red-600",
      warning: "text-yellow-800",
      info: "",
      success: "text-green-400",
    },
  },
}
